### ISSUE TITLE
Missing file update after move

### ISSUE THREAD

**Issue by valoq** [gokcehan/lf#1903]
There appears to be another strange bug regarding the watch feature that is triggered by moving files - But it is unreliable to reproduce.

When I found this I could reproduce the issue reliably like this:

Case A)
- files a, b, c and d are marked and moved to a a child directory (the original path is still visible in lfs left pane)
- The files are moved and displayed correctly in the new directory while their old location is correctly updated as empty

Case B)
- files a, b, c and d are in a directory, file a is deleted, files b, c and d are marked and moved to the subdirectory.
- The files are moved and displayed correctly in the new directory but they are still shown in the old path as well until a manual refresh is triggered.

After observing Case B) and repeating the bug several times, I rebooted and the bug could no longer be reproduced, leaving me with Case A) again

**Comment by joelim-work** [comment]
I tried case B and couldn't reproduce at all. Have you tried logging the fsnotify events to see what is going on? When moving files there should be `Rename` events (for the previous directory) and `Create` events (for the new directory).

**Comment by valoq** [comment]
Ok I found the trigger:

Case 1) If I create a new directory and move files there, the previous file location is not updated
Case 2 )If the files are instead moved to a preexisting directory, the bug is not triggered.


Case 1

```
2025/02/04 18:57:51 fsnotify event: CREATE        "/home/testuser/x"
2025/02/04 18:57:56 fsnotify event: RENAME        "./aa.png"
2025/02/04 18:57:56 fsnotify event: CREATE        "/home/testuser.homedir/x/aa.png" ← "./aa.png"
2025/02/04 18:57:56 fsnotify event: RENAME        "./bb.png"
2025/02/04 18:57:56 fsnotify event: CREATE        "./bb.png" ← "./bb.png"
2025/02/04 18:57:56 fsnotify event: CREATE        "./cc.png"
2025/02/04 18:57:56 fsnotify event: CREATE        "./dd.png"
```


Case 2

```
2025/02/04 18:58:20 fsnotify event: RENAME        "/home/testuser/aa.png"
2025/02/04 18:58:20 fsnotify event: CREATE        "/home/testuser/x/aa.png" ← "/home/testuser/aa.png"
2025/02/04 18:58:20 fsnotify event: RENAME        "/home/testuser/bb.png"
2025/02/04 18:58:20 fsnotify event: CREATE        "/home/testuser/x/bb.png" ← "/home/testuser/bb.png"
2025/02/04 18:58:20 fsnotify event: RENAME        "/home/testuser/cc.png"
2025/02/04 18:58:20 fsnotify event: CREATE        "/home/testuser/x/cc.png" ← "/home/testuser/cc.png"
2025/02/04 18:58:20 fsnotify event: RENAME        "/home/testuser/dd.png"
2025/02/04 18:58:20 fsnotify event: CREATE        "/home/testuser/x/dd.png" ← "/home/testuser/dd.png"
```

For some reason creating a new directory causes fsnotify to work with the relative path of the files instead of the absolute one.

In some cases the second mount path was also logged in the second case, so Im not sure this is related.

**Comment by joelim-work** [comment]
That's strange, I have never seen relative paths before. I was always under the impression that all paths provided by fsnotify would be absolute.

In any case I tried it again just now with the following commands but for me I only got absolute paths so I couldn't reproduce:

```sh
# test directory should contain a.txt, b.txt, c.txt and d.txt
# run after starting lf in test directory
mkdir foo
mv a.txt foo
mv b.txt c.txt d.txt foo
```

```
2025/02/05 14:33:22 event: CREATE        "/home/joelim/test/foo"
2025/02/05 14:33:24 event: RENAME        "/home/joelim/test/a.txt"
2025/02/05 14:33:24 event: CREATE        "/home/joelim/test/foo/a.txt" ← "/home/joelim/test/a.txt"
2025/02/05 14:33:27 event: RENAME        "/home/joelim/test/b.txt"
2025/02/05 14:33:27 event: CREATE        "/home/joelim/test/foo/b.txt" ← "/home/joelim/test/b.txt"
2025/02/05 14:33:27 event: RENAME        "/home/joelim/test/c.txt"
2025/02/05 14:33:27 event: CREATE        "/home/joelim/test/foo/c.txt" ← "/home/joelim/test/c.txt"
2025/02/05 14:33:27 event: RENAME        "/home/joelim/test/d.txt"
2025/02/05 14:33:27 event: CREATE        "/home/joelim/test/foo/d.txt" ← "/home/joelim/test/d.txt"
```

---

I searched the issue tracker in fsnotify and the only relevant thing I could find was https://github.com/fsnotify/fsnotify/issues/160. It's possible that the path registered by `lf` was relative, which could cause the updates to also contain relative paths. Could you try logging the actual paths watched here: https://github.com/gokcehan/lf/blob/4f0a5d6211f56a42735af09d58ec6691aac35b64/watch.go#L67-L76

`lf` tries to ensure that all paths are absolute for simplicity - if for some reason the path being registered is relative then you'll have to debug further, but if it's absolute then it indicates that it's an issue with fsnotify.

**Comment by valoq** [comment]
When logging all path that are added to the watcher, the loggest path list are identical between the process that triggered the bug and the one where lf works as expected. In both cases the path are absolute and include both the previous path and the path of the newly rcreated directory

I also confirmed/reproduced the bug on a partition without double mount to rule that out.

The only place where the relative path shows up is in the fsnotify event log

**Comment by valoq** [comment]
I did some more tests to find the change that introduced the bug:

When I use the current master branch and set fsnotify back to version 1.7.0 the bug still remains
When I use lf version r33 with either fsnotify version 1.7.0 or 1.8.0 the bug does not appear.

Therefore it seems to be an issue that was introduced with the recent changes.

**Comment by joelim-work** [comment]
There's not much I can do without a minimal example that actually reproduces the issue. If you have logged the calls for `Watcher.Add` in `lf`, can you mimic the behavior in a [test program](https://github.com/fsnotify/fsnotify?tab=readme-ov-file#usage) outside of `lf` and get the same result?

Also are you absolutely sure there are no relative paths being watched? You can use [`Watcher.WatchList`](https://pkg.go.dev/github.com/fsnotify/fsnotify#Watcher.WatchList) to check.

**Comment by valoq** [comment]
> There's not much I can do without a minimal example that actually reproduces the issue.

To reproduce the issue:

1. Start lf
2. create a new directory 
3. cut a file
4. move to newly created direcoty
5. paste the file

The file will now be shown in both the previous and the new directory.

**Comment by joelim-work** [comment]
I meant an example that I can actually reproduce. I tried the above steps and it works fine for me:

1. `lf -config /dev/null -command 'set watch true'`
2. `$mkdir foo`
3. Use `d` to cut
4. Use `l` to enter the new directory
5. Use `p` to paste

With only two users in this discussion, there's not much sample size to help investigate the roost cause, and the problem seems to have a 'works on my machine' nature.

**Comment by valoq** [comment]
It seems to have been a config issue after all.
When I use `$mkdir foo` lf behaves as expected, but I had used `:mkdir foo` instead, using the mkdir function I previously found in the wiki

```
cmd mkdir %{{
    IFS=" "
    mkdir -p -- "$*"
    lf -remote "send $id select \"$*\""
}}
```

This seems to be what causes the bug for some reason, not lf itself

**Comment by valoq** [comment]
Ok this seems to still be an issue after all but more complicated.
While moving a lot of files recently I noticed several intances where this bug appeared in one form or another.
Despite now using the default lfrc options for mkdir it also happened again when moving files to new directories but the bug also appeared after decompressing files and after moving files into trash.

In case it becomes relevant, this is my config for the mentioned functions:

```
cmd extract ${{
    set -f
    ouch decompress $f
}}

map a : extract; reload

cmd trash %trash-put -- $fx
map D trash
```

In multiple cases, the watch feature stopped working entirely after the bug appeared. Moved, copied and deleted files were no longer updated at all. This happened on a directory that was not mounted more then once, ruling out the fsnotify bug https://github.com/fsnotify/fsnotify/issues/667 as the cause.

Unfortunately I did not yet manage to reproduce this issue reliably.

**Comment by jake-stewart** [comment]
@joelim-work @valoq reproducible example. hopefully the same bug.

https://github.com/user-attachments/assets/1a5274da-8fb0-4d4c-9300-c202d51cbfa0

**Comment by joelim-work** [comment]
@jake-stewart Are you using a completely blank configuration with only `set watch true`? Like below:

```sh
lf -config /dev/null -command 'set watch true'
```

I tried doing the exact same thing and couldn't reproduce.

https://github.com/user-attachments/assets/202f2701-47ef-4175-9bd7-53b504e7a98e

I don't know if it's the same issue as OP, you can try logging the actual fsnotify events to see if it contains relative paths using the following patch:

```diff
diff --git a/watch.go b/watch.go
index d4f70d3..d4e38a0 100644
--- a/watch.go
+++ b/watch.go
@@ -81,6 +81,7 @@ func (watch *watch) loop() {
 	for {
 		select {
 		case ev := <-watch.events:
+			log.Printf("fsnotify event: %v", ev)
 			if ev.Has(fsnotify.Create) {
 				dir := filepath.Dir(ev.Name)
 				watch.addLoad(dir)
```

**EDIT:** I have no idea why the background in the video is green, but it doesn't change anything.

**Comment by jake-stewart** [comment]
Sorry, didn't know about that option and assumed it was a bug. It works great now. @joelim-work

**Comment by valoq** [comment]
I do not think we can reproduce this reliably. From what I have seen this issue happens randomly and appears to break the fsnotify feature entirely when it does, but without causing lf to crash.

Still trying to catch anything useful in the event logs but so far the only thing I found was the relative path as mentioned above.

**Comment by valoq** [comment]
This bug has also been observed on entirely different systems running Debian testing on different hardware. 
I have yet to log anything useful or find a reproducible trigger, but my suspicion is a race condition bug in fsnotify starting with version 1.8.0 since this issue was not observed in previous releases

**Comment by valoq** [comment]
#1953 includes fixes for race conditions in fsnotify which may be the trigger of this issue.
So far I have not yet encountered the issue again with lf build against fsnotify version 1.9.0 but that doesn't need to mean anything since it occurs quite randomly.
However I would like to suggest a new release to allow these fixes to make it into the Debian Trixie, which is going for its soft freeze in a week from now.

**Comment by valoq** [comment]
After updating fsnotify to 1.9.0 this issue has not appeared again and seems to be fixed in lf v35

**Comment by valoq** [comment]
Unfortunately, it happened again now and seems to be unrelated to the recent fsnotify update.

To recap this issue:

Moving files to new directories will sometimes cause the watch feature to stop working

1. It triggers very unreliably, indicating a possible race condition
2. Once it happened a single time, the watch feature entirely stops working, likely because fsnotify crashed
3. It could be observed on both Arch and Debian using different setups and hardware.


Reproduction (unreliable but this aligns with what was done every time the issue was observed)
```
    lf -config /dev/null -command 'set watch true'
    $mkdir foo
    Use d to cut
    Use l to enter the new directory
    Use p to paste
```

**Comment by valoq** [comment]
Ok I finally managed to reproduce the issue:

1. create directory "test" and a sub directory "test/a"
2. create a "testfile" in test
3. rename test to test2
4. move "testfile" to test/a
5. "/test/a" will remain empty until manual refresh is triggered


The fsnotify logs show that file events after the rename continue to use the old path before the rename



```
2025/05/10 23:50:14 hi!
2025/05/10 23:50:14 reading file: /home/eve/.config/lf/colors
2025/05/10 23:50:14 reading file: /home/eve/.config/lf/icons
2025/05/10 23:50:14 loading files: []
2025/05/10 23:53:45 reading file: /dev/null
2025/05/10 23:50:14 loading files: []
2025/05/10 23:50:23 pushing keys %mkdir<space>
2025/05/10 23:50:26 shell-pipe: mkdir test
2025/05/10 23:50:26 fsnotify event: CREATE        "/tmp/test"
2025/05/10 23:50:31 pushing keys %mkdir<space>
2025/05/10 23:50:39 shell-pipe: mkdir a
2025/05/10 23:50:39 fsnotify event: CREATE        "/tmp/test/a"
2025/05/10 23:50:55 shell: touch testfile
2025/05/10 23:50:55 fsnotify event: CREATE        "/tmp/test/testfile"
2025/05/10 23:50:55 fsnotify event: CHMOD         "/tmp/test/testfile"
2025/05/10 23:51:02 fsnotify event: RENAME        "/tmp/test"
2025/05/10 23:51:02 recv: load
2025/05/10 23:51:02 reading directory: open : no such file or directory
2025/05/10 23:51:02 fsnotify event: CREATE        "/tmp/test2" ← "/tmp/test"
2025/05/10 23:51:02 fsnotify event: RENAME        "/tmp/test"
2025/05/10 23:51:04 saving files: [/tmp/test2/testfile]
2025/05/10 23:51:04 recv: sync
2025/05/10 23:51:04 loading files: [/tmp/test2/testfile]
2025/05/10 23:51:06 loading files: [/tmp/test2/testfile]
2025/05/10 23:51:06 saving files: []
2025/05/10 23:51:06 fsnotify event: RENAME        "/tmp/test2/testfile"
2025/05/10 23:51:06 recv: load
2025/05/10 23:51:06 saving files: []
2025/05/10 23:51:06 fsnotify event: CREATE        "/tmp/test/a/testfile" ← "/tmp/test2/testfile"
2025/05/10 23:51:06 recv: sync
2025/05/10 23:51:06 loading files: []
2025/05/10 23:51:06 recv: sync
2025/05/10 23:51:06 loading files: []
2025/05/10 23:51:08 bye!
```

The next question is, if this is an issue in lf or fsnotify

**Comment by joelim-work** [comment]
> * create directory "test" and a sub directory "test/a"
> * create a "testfile" in test
> * rename test to test2
> * move "testfile" to test/a
> * "/test/a" will remain empty until manual refresh is triggered

I can reproduce this consistently - turns out there's a bug when a path component in the CWD is renamed, but it happens so infrequently in practice that no issue has been raised before. I have fixed this in #1982.

That being said I have no idea if it's the same issue as the one you originally reported, since the latter doesn't happen consistently and I never managed to reproduce it at all.

**Comment by valoq** [comment]
> > * create directory "test" and a sub directory "test/a"
> > * create a "testfile" in test
> > * rename test to test2
> > * move "testfile" to test/a
> > * "/test/a" will remain empty until manual refresh is triggered
> 
> I can reproduce this consistently - turns out there's a bug when a path component in the CWD is renamed, but it happens so infrequently in practice that no issue has been raised before. I have fixed this in [#1982](https://github.com/gokcehan/lf/pull/1982).

Thank you, Im glad we finally found the cause of this issue.
Unfortunately the fix does not seem to work as intended yet, as I can still reproduce the problem.

**Comment by joelim-work** [comment]
Oh sorry I got confused about your steps to reproduce and stumbled upon a completely different bug.

I had a closer look at your logs and the key line is this:

```
2025/05/10 23:51:06 fsnotify event: CREATE        "/tmp/test/a/testfile" ← "/tmp/test2/testfile"
```

So the correct location is `/tmp/test2/a/testfile`, but the path provided by fsnotify is `/tmp/test/a/testfile`, which is a bug on their side.

**Comment by valoq** [comment]
It seems the bug wont be fixed anytime soon in the fsnotify project: https://github.com/fsnotify/fsnotify/issues/694#issuecomment-2886306684

But I suppose we could add a workaround in lf that removes the renamed path and adds a new watcher after rename?

**Comment by joelim-work** [comment]
> But I suppose we could add a workaround in lf that removes the renamed path and adds a new watcher after rename?

I guess you can try experimenting with the code to see if this is feasible.

Though I'm probably more interested in just waiting to see if recursive watches works better. In theory it would be possible to just recursively watch the root directory once, so long as it's possible to filter certain subdirectories that update frequently and cause a lot of spam.

**Comment by joelim-work** [comment]
The commit 20f1b20 doesn't remove watches for outdated paths, it removes watches if the user switches to a different part of the filesystem (e.g. stop watching `/home/user/foo/` if the user changes the directory to `/home/user/bar`). In this case no paths are being removed/renamed so it is not relevant to this issue.

So actually fsnotify automatically removes watches old renamed/removed paths, this is stated in their [documentation](https://pkg.go.dev/github.com/fsnotify/fsnotify#Watcher.Add):

> A watch will be automatically removed if the watched path is deleted or renamed. The exception is the Windows backend, which doesn't remove the watcher on renames.

**Comment by valoq** [comment]
> The commit [20f1b20](https://github.com/gokcehan/lf/commit/20f1b20c17997cf72648c23cd47ca83142f1e4ae) doesn't remove watches for outdated paths, it removes watches if the user switches to a different part of the filesystem (e.g. stop watching `/home/user/foo/` if the user changes the directory to `/home/user/bar`). 

~~Yes, but if the user renamed //home/user/foo/ to /home/user/foo2/ and then moved to /home/user/bar, the old outdated path is removed.~~ Update: Sorry I guessed wrong here, it was another commit mentioned below

I will test this again to find the specific commit but somewhere around the removal commit, this issue appeared, while in v33 it is not reproducible at all.


 
> So actually fsnotify automatically removes watches old renamed/removed paths, this is stated in their [documentation](https://pkg.go.dev/github.com/fsnotify/fsnotify#Watcher.Add):
> 
> > A watch will be automatically removed if the watched path is deleted or renamed. The exception is the Windows backend, which doesn't remove the watcher on renames.

Yet the logs show the outdated path remaining in fsnotify and the fsnotify project wont fix it https://github.com/fsnotify/fsnotify/issues/694#issuecomment-2887670593

**Comment by joelim-work** [comment]
Since variant 1 is fixed in `fsnotify` 1.9.0, I think there is no need to discuss it further.

---

As for variant 2, the root cause is explained here: https://github.com/fsnotify/fsnotify/issues/694#issuecomment-2886306684. The sequence of events is like this:

1. The user creates a watch for `/tmp/test/a`
2. A watch descriptor is returned from calling the [`inotify_add_watch`](https://man7.org/linux/man-pages/man2/inotify_add_watch.2.html) system call
3. The path `/tmp/test/a` is then associated with that watch descriptor in `fsnotify`
4. The user renames `/tmp/test` to `/tmp/test2`
5. Nothing happens since there were no changes to the files *inside* the `a` directory
6. The user creates a new file `testfile` inside the `a` directory
7. An [`inotify_event`](https://man7.org/linux/man-pages/man7/inotify.7.html) is received, which contains the `mask` (indicates a create event), `name` (the new file is called `testfile`), and `wd` (watch descriptor of the registered watch).
8. `fsnotify` then uses the watch descriptor from the event to look up the saved path (still `/tmp/test/a`) and then combines that with the filename, so the final result is `/tmp/test/a/testfile`.

Since watching is based on watch descriptors and not paths, the `inotify` API will not be able to tell you that the *path* of a watched directory has been changed (e.g. `/tmp/test/a` to `/tmp/test2/a`). Instead, the mapping between watch descriptors and paths is maintained by `fsnotify` but the implementation is incomplete. In this case if the user creates a watch for `/tmp/test/a`, `fsnotify` should additionally watch parent directories like `/tmp` and use rename events (`/tmp/test` to `/tmp/test2`) to update the mapping accordingly.

One suggestion might be to handle the path mapping directly inside `lf`, but I do not think this is a good idea:

- Properly detecting renames from `fsnotify` is not foolproof as there is not one but two separate events (`RENAME` and `CREATE`). The `inotify` API provides a `cookie` field which is used to link them together, but this is not exposed from `fsnotify`. Using other techniques like waiting for a timeout to link events is improper and might end up causing other bugs.
- The mapping between paths and watch descriptors is already maintained by `fsnotify`, but it does not handle all cases. Maintaining an additional mapping inside application code is a hacky workaround and somewhat defeats the purpose of using `fsnotify` in the first place, and furthermore will reduce the motivation to properly address the issue inside `fsnotify`.
- Adding a workaround in `lf` will not fix the same issue in any other applications that also use `fsnotify`.

---

On the topic of recursive watches, using it sounds like a good idea when it is finally released, but there is no guarantee that it will not contain any bugs. I was thinking of just recursively watching the root directory, but watching `/dev` is undesirable as updates to `/dev/tty` causes too much spam. I doubt there is any way to blacklist directories during recursion, so maybe the solution is to just recursively watch all subdirectories of `/` excluding `/dev` instead.

**Comment by valoq** [comment]
Thank you for the detailed explanation

I agree that recursive watches would be ideal to address this, but it may be some time until it is actually implemented and released in fsnotify. Meanwhile this bug make lf behave unreliable when moved files suddenly disappear.

Since this issue was not present before https://github.com/gokcehan/lf/pull/1895, and even this second variant is not present in previous releases (v33) when it is used with fsnotify 1.9.0, we could avoid triggering the issue, even if the core of the problem remains in fsnotify.

**Comment by joelim-work** [comment]
No, I tried r33 and the second variant can be reproduced there too (same issue as what I described above due to `fsnotify`):

1. Create `~/dir/subdir`
2. Start `lf` at `~/dir` with the cursor on `subdir`
3. Run `&mv ~/dir ~/dir2` on the command line
4. Run `&touch ~/dir2/subdir/testfile` on the command line

**Comment by valoq** [comment]
It looks like there are more variants of this bug. I tested it by moving a preexisting file around and in v33 that didn't trigger the issue. But workarounds in lf for all those cases seem like a bad idea now, so we certainly need fsnotify addressing the rename bug for a real solution.

In the meantime, anyone who uses the watch feature can add the period option in addition as this will address the missing updates from fsnotify.

**Comment by CatsDeservePets** [comment]
Hello @valoq!
There have been quite a bit of bug fixes related to file upates in `lf` lately, the most recent being
- https://github.com/gokcehan/lf/pull/2181
 
Please install the just released `r39` version and verify whether the bug is fixed now.

**Comment by valoq** [comment]
> Please install the just released `r39` version and verify whether the bug is fixed now.

This issue still exists in version 39 and can still be reproduced with the steps documented [here](https://github.com/gokcehan/lf/issues/1903#issuecomment-2869172041) 
I dont think we can fix this in lf since the bug is in fsnotify. We will need to wait for recursive watches to be added to fsnotify for this to be addressed. See https://github.com/fsnotify/fsnotify/pull/676
