### ISSUE TITLE
Symbolic link previews

### ISSUE THREAD

**Issue by peterhen0** [gokcehan/lf#31]
When there the cursor is over a symbolic link to a directory, the preview pane does not display the correct contents, however descending into that directory is fine.

**Comment by gokcehan** [comment]
@peterhen0 This sounds like the same issue in #25. We pushed a fix for that some time ago. Can you confirm you have the latest version?

**Comment by peterhen0** [comment]
Sorry about that! you were totally right. Still getting used to GitHub.

**Comment by gokcehan** [comment]
No problem @peterhen0 :) Closing this issue now. Feel free to write again if you continue to have problems after an update.
