### ISSUE TITLE
Flickering "loading…​"

### ISSUE THREAD

**Issue by igorhub** [gokcehan/lf#414]
Greetings!

First, let me thank you for developing lf! I discovered it earlier today (over at r/linux), and I’m very impressed so far. I’ve been looking for a fast and extensible ranger replacement for a long time, and lf looks like an exactly right fit.

One unpleasant effect that jumped at me immediately is caption 'loading…​' flickering each time I go up and down the file list. I can see why it’s useful for large directories, but, unless the loading takes more than, say, 100 ms, it’s just a distraction.

Conversation at #277 gives me an impression that there is a setting for it, but I can’t find anything in the documentation file, nor in lfrc.example.

**Comment by YerinAlexey** [comment]
You can preload multiple files/directories by putting
```
set preview current COUNT
```
in your `lfrc`. Instead of `COUNT` you need to put how many files/dirs to preload

**Comment by gokcehan** [comment]
@igorhub Thank you for the kindness. That issue is still open so there are no settings for it. Closing this as duplicate.

**Comment by igorhub** [comment]
Do I understand correctly that you consider it a duplicate of #277? I didn’t intend it as a duplicate of #277.

In #277, smhmd asked for a rather complex feature for unclear reasons. (He mentioned blinking 'loading…​' at the end of the discussion, so maybe that was his whole problem all along. But maybe he had a bigger picture in mind, who knows.)

What I’d like to do is, first a foremost, to report a persistent problem — the right pane is blinking upon moving up and down the file list. I hoped this was a solved problem, because you said you didn’t see it on your machine. I see it both on my SSD and HDD, and especially on my remote drive.

As for the solution, it can be much simpler than what smhmd suggests. It seems, at a first glance, that all you need to do is to delay redrawing until the the preview text is ready, and only show 'loading…​' upon reaching a timeout of 100-200 ms. I don’t know how hard it is to implement in Go, from what I’ve read its concurrency system is well-suited for such workflows.

As an aside, I’ll admit that I notice it less the more I use lf. Looks like I’m getting used to it. Still, it gives a bad first impression, and first impressions are important. Slick look and responsive feel is a primary feature for us ranger refugees.

**Comment by gokcehan** [comment]
@igorhub Sorry I didn't realize you meant this as a separate suggestion. We have too many requests but not enough contributors, and some people like to create duplicate issues to get more attention to their favorite missing feature, so I tend to close similar issues as duplicate. If I understand you correctly though, you are complaining about the same issue aimed in that other issue, so we might as well discuss this in the same context.

Initial implementation of `lf` did not have async loading. This works most of the time, but it creates a jammed feeling when you try to move fast in the list since directory load times are different and movement is blocked until a directory or file is loaded in the ui. Async loading implementation was generally well received by most users. You might be able to check out older releases to see how it feels. You may also experience a similar feeling when you're on a slow network filesystem and you have `set dircounts` and `set info size` enabled.

I guess what you're suggesting is a hybrid approach with an initial sync loading and falling back to async loading when it takes too long. I think this will still have the same issue as before since loading times will be different for each item. In the most general case, most things should already be loaded under 100ms anyway, unless you're on a network filesystem and such, so this won't be much different than sync loading.

There are two possible reasons for flickering, IO bottleneck or UI bottleneck. There is nothing much we can do about the IO bottleneck. UI bottleneck happens for async loading of non-cached items since we need to draw two frames in a short amount of time, one for loading, the other for the actual. As much as I don't like complicating things, the proactive caching suggestion given in the other issue seems to me like the proper solution to this issue, otherwise I worry we might end up with the same jamming feeling as before. We already have functions for async loading of items, we just need to find proper places to trigger these calls. This may or may not be difficult, I just didn't have time yet so far, and it seems that noone else did either.

Lastly, you might be able to use a faster terminal to deal with the IO bottleneck. Displaying two frames should not be an issue these days, and terminals only redraws the portion that are modified so it's not even two frames. I'm using `alacritty` these days. In general, any gpu rendering terminal should be fine for this purpose. Navigating through `/usr/include` I can't see `loading...` in directories. I can see it in files but only when I have highlighting enabled so it's likely an IO bottleneck. I have now tried this on a `libvte` terminal and `xterm` and I think flickering is more noticeable on these terminals.

**Comment by igorhub** [comment]
@gokcehan I don’t suggest hybrid approach. I think fully async approach is the way to go.

I’ve re-read my previous comment and I see I’ve made an error of omission. When I wrote "delay redrawing" what I had in mind was "delay redrawing the right pane". Instead of filling it with 'loading…​' for a split second, let it stay the same for a split second. The only potential problem I see with that happens when you move down the list really fast, and your preview is really slow, so you are down a few dozen items, but still see the stale preview. Seems like an unlikely situation, even on network drives, unless you really overload your preview function.

And, by the way, thanks for mentioning alacritty! I use it indeed, but your comment prompted me to look for possible problems, and I found one. It seems to fell back to CPU rendering due to configuration error on my part. I fixed it now, and the flickering situation improved considerably.

**Comment by igorhub** [comment]
@gokcehan I also noticed that `reload` causes the same flickering effect.
Here again, allowing the screen to stay stale for a brief moment would make it look totally seamless.

**Comment by igorhub** [comment]
@gokcehan Found a new related bug (no need to create a separate issue, I guess).

I have the following code in my config:

    map D %trash $fx

After upgrading from `r13` to `master` (to get access to `on-cd`), it started to blink each time I trash a file.

Running `r13` and `master` alongside, I can confirm: `master` blinks, and `r13` runs smoothly.

**Comment by YerinAlexey** [comment]
> @gokcehan Found a new related bug (no need to create a separate issue, I guess).
> 
> I have the following code in my config:
> 
> ```
> map D %trash $fx
> ```
> 
> After upgrading from `r13` to `master` (to get access to `on-cd`), it started to blink each time I trash a file.
> 
> Running `r13` and `master` alongside, I can confirm: `master` blinks, and `r13` runs smoothly.

For me switching to `r13` didn't change anything. Both are blinking

**Comment by igorhub** [comment]
`r13` only blinks for me if I change the command from shell-pipe to to normal shell: `$trash $fx` (but that's how it supposed to work I believe).

**Comment by igorhub** [comment]
I think I was unclear (sorry about that): in `r13` only the right pane blinks, in `master` both the right pane and the file list blinks.

**Comment by YerinAlexey** [comment]
> in `r13` only the right pane blinks, in `master` both the right pane and the file list blinks.

Very strange. I didn't notice file list blinking neither in `master`, nor in `r13`

**Comment by igorhub** [comment]
Do I understand correctly that when I type "go get -u github.com/gokcehan/lf" I get the master? (I'm not familiar with Go and its build system.)

**Comment by YerinAlexey** [comment]
> Do I understand correctly that when I type `go get -u github.com/gokcehan/lf` I get the master?

You're correct

**Comment by igorhub** [comment]
I don't know what to make of it, then. I removed all code from my `lfrc`, leaving only `map D %trash $fx`, and I keep seeing the blink each time I trash a file. It is quite long, impossible not to notice.

**Comment by YerinAlexey** [comment]
> I don't know what to make of it, then. I removed all code from my `lfrc`, leaving only `map D %trash $fx`, and I keep seeing the blink each time I trash a file. The blink is quite long, impossible not to notice.

This happens **only** when you trash a file? If so, try using:
```
cmd trash &{{
  trash $fx
  lf -remote "send $id load"
}}
map D trash
```

**Comment by igorhub** [comment]
> This happens **only** when you trash a file?

When I change `trash` to `rm`, it only blinks only occasionally (like 20% of the time), and the blink itself feels shorter.



> If so, try using:
> 
> ```
> cmd trash &{{
>   trash $fx
>   lf -remote "send $id load"
> }}
> map D trash
> ```

Same result.

**Comment by gokcehan** [comment]
@igorhub @YerinAlexey There was indeed a recent change in ffdcb71897e6a4da0877cada796312d42dac0363. `select` command was not working with modified directories, so these directories are now marked as loading so it shows up a loading screen.

**Comment by Limero** [comment]
I just updated from r14 to r15 and if I navigate to the `/tmp` directory the "loading" flickering happens but it doesn't on any other directories for me. After running `git bisect` I can confirm that it's ffdcb71897e6a4da0877cada796312d42dac0363 is causing the problem. Running commits prior to that doesn't have the flickering.

**Comment by gokcehan** [comment]
I have pushed a fix to avoid flickers with loading directories. We now show directories with a previous file list even if they are loading. Ideally we should add something like a loading icon somewhere in the ui.

**Comment by Limero** [comment]
The flickering is gone for me now. Thank you!

**Comment by bluesuncat** [comment]
This is still an issue with the current git version of lf and frankly I find it to be the most annoying problem of lf.

It can be completely avoided by removing https://github.com/gokcehan/lf/blob/3fc1db5d1426d417869857d4b6cf090f05d73d26/ui.go#L264 and https://github.com/gokcehan/lf/blob/3fc1db5d1426d417869857d4b6cf090f05d73d26/ui.go#L365 but this would also prevent a loading message when big files/directories are rendered for preview, which is what this would actually be useful for.

Currently, instead of displaying the loading message in the rare case of large files/directories being read, it is displayed every single time for every single file for like 0.1 seconds, which doesn't allow to read it properly either.

The suggestion to wait a second before displaying the "loading" message still seems to be the best solution to me.

**Comment by ilyagr** [comment]
@bluesuncat , with your suggested patch, there is still flickering, just with a fully black region instead of the "loading..." message. Is this a huge improvement in your mind?

If it is, waiting a bit before printing "loading..." seems likely doable. Making the flicker disappear entirely seems harder, but perhaps @joelim-work has some thoughts.

**Comment by bluesuncat** [comment]
After running lf with the mentioned lines removed, I find it is a moderate improvement, but the main benefit would be that it no longer looks "bugged"
When an application shows a notification for 0.1 seconds, its reasonable to assume this is not how it was intended and feels broken, so even if it still flashes, there should be a solution to the general issue

**Comment by ilyagr** [comment]
A hybrid approach I just thought of would be to layer the `loading...` message on top of the previous content of the preview. Then, there'd be much less flickering, but the user will also be able to tell when the content of the pane is stale.

**Comment by joelim-work** [comment]
I'm not particularly sure if I want to see both the `loading...` message and the previous preview at the same time, but that's just my preference. Also, correct me if I'm wrong, but I don't think it's possible to layer a message on top of the preview if it's an image preview rendered using `ueberzug`.

Another (probably crazy and not so good) idea I have is to allow users to specify the specify the format of the `loading...` message, so that if it is configured to be a blank string, the effect would be the same as deleting those lines of code.

**Comment by ilyagr** [comment]
No, I was thinking of textual previews only, something like replacing their first line (last line might be even better, I'm not sure) with a `loading...` message. Then, only one line would be flickering instead of the entire preview.

**Comment by joelim-work** [comment]
I would prefer to keep the behaviour consistent regardless of whether I'm switching from a text preview or an image preview. Maybe it's possible to reserve the bottom line of the preview window (or even an area outside the preview window) for the purpose of displaying the `loading...` message.

I think the problem now is that there are multiple ways to approach this, but I don't know which one is preferable to everyone else.

**Comment by bluesuncat** [comment]
@ilyagr Im not sure I understand the reasoning behind displaying the loading message on top of the previous preview.
In my head this would look even more broken and I cannot see this providing any use.

Showing an empty preview and waiting for one second (or perhaps 0.5) before displaying the loading message wounds like the cleanest solution and would also be very easy to implement.

**Comment by joelim-work** [comment]
I think showing an empty preview and waiting for X amount of time before displaying the loading message would provide the most intuitive user experience out of all these options.

I guess you would have to implement in such a way so that it is possible to cancel an upcoming loading message if another preview is requested (e.g. the user selects another file, the file is updated, the terminal window size changes, etc.).

For example consider the following scenario:

1. The user selects a file. A preview is not immediately available and the loading message is triggered to display after 1 second
2. 0.9 seconds later, the user selects another file. 
3. 0.1 seconds after that, the loading message from selecting the first file appears.

The result of steps 2 and 3 means that it is possible to select a file and still see a loading message pop up extremely quickly.

**Comment by bluesuncat** [comment]
Would it be possible to measure the time taken by the preview script and display the loading if there is no response after one second? Not sure how to do this in go though

**Comment by bluesuncat** [comment]
I can't say that I fully understand yet how the code works, but after playing around with the this bug for a bit, I suspect it probably needs more then adding a delay to the loading message, especially after https://github.com/gokcehan/lf/commit/4a443cae58ffe417c4aebedd88aeae6380bf190c (correctly) reintroduces this flickering to open actions as well.

Right now using lf, especially with a preview script, includes a lot of flickering and I hope we can agree that this issue should be a blocker for the next release.

**Comment by joelim-work** [comment]
I decided to have a crack at this, see #1154. This uses the approach described above - draw nothing, then the `loading...` message after one second.

It gives significant improvement for me already, I don't see the loading message anymore unless I deliberately put a `sleep` in my previewer script. Hopefully it works for others too.

**Comment by joelim-work** [comment]
BTW @gokcehan has mentioned the possibility of not delaying the loading message, and instead just moving it to a different area (I think somewhere in the lower right status bar is best). I think it might be worth considering.

**Comment by joelim-work** [comment]
Hi @bluesuncat,

Thanks for your feedback. The patch should delay the loading message for both files and directories. I suppose it might be possible that your directories are taking over 100 milliseconds to load, in which case the preview timer times out and will display the loading message. You could try experimenting by changing the [timeout](https://github.com/gokcehan/lf/pull/1154/files#diff-709f5e973a2336a6ffa87ae2b743b4a850de2c5c4c61e68a2cb0efc5352db00bR351) and/or inserting `sleep` into your preview script to simulate a longer loading time, but keep in mind the following:

- You will need to `set dirpreviews` to your config file to have the previewer script apply to directories
- `lf` loads a few directories upon startup, so it might be easier to start it first and then add the `sleep` statement

Finding the right balance for the timeout period is tricky - if the timeout is too large then it takes too long for the user to be notified that the preview is being loaded, and if the timeout is too small then there won't be enough time for the preview to actually load. Depending on how things turn out, I might consider adding a `previewTimeout` option to the config file to allow users to customise the timeout period.

As for the flickering when opening files, I think this is actually a different issue. Previously I thought you were referring to just the loading message, but it looks like you also have an issue with the preview being refreshed? Now that I think about the problem more, if you are using the default `open` command, then this invokes the `$OPENER` _asynchronously_, and you could make the argument that there's no point refreshing the preview in this case, since the redraw happens immediately without waiting for the shell command to finish.

Would you be able to apply the following patch to the `app.runShell` command and see if that fixes your issue?

```diff
--- a/app.go
+++ b/app.go
@@ -566,7 +566,8 @@ func (app *app) runShell(s string, args []string, prefix string) cleanFunc {
                anyKey()
        }

-       app.ui.loadFile(app, true)
+       volatile := prefix != "&"
+       app.ui.loadFile(app, volatile)

        switch prefix {
        case "%":
```

**Comment by bluesuncat** [comment]
> Would you be able to apply the following patch to the `app.runShell` command and see if that fixes your issue?
> 
> ```diff
> --- a/app.go
> +++ b/app.go
> @@ -566,7 +566,8 @@ func (app *app) runShell(s string, args []string, prefix string) cleanFunc {
>                 anyKey()
>         }
> 
> -       app.ui.loadFile(app, true)
> +       volatile := prefix != "&"
> +       app.ui.loadFile(app, volatile)
> 
>         switch prefix {
>         case "%":
> ```
> 

This works perfectly and prevents the redraw when opening files.

I also tested your latest changes, but the issue with the loading message for directory remains.
Even after setting previewtimeout to 5000, I still see a flickering loading message for directories even if they are displayed after less then 0.1 seconds. This is also the case if I remove all of my lfrc and only set the previewtimeout option.

After looking at your changes it seems that for files you added a previewLoading condition that I do not see for directories. Is this whats missing perhaps?

**Comment by joelim-work** [comment]
Hi @bluesuncat 

So about the flicker when opening files, I was looking through the commit history and apparently someone already solved this by defining a custom `open` command, have a look at their [pull request](https://github.com/gokcehan/lf/pull/991/files) and see if the example works for you. If not then you can just submit the above patch as a separate pull request (I think this should be treated separately to the loading message).

As for the directories issue, after some debugging I found that specifically for the code that handles directories, there was a race condition caused by the fact that the `previewLoading` flag was being set in a different thread, and sometimes the UI would get drawn before that happens. I have pushed another commit to fix this, would you be able to try again?

**Comment by bluesuncat** [comment]
> Hi @bluesuncat
> 
> So about the flicker when opening files, I was looking through the commit history and apparently someone already solved this by defining a custom `open` command, have a look at their [pull request](https://github.com/gokcehan/lf/pull/991/files) and see if the example works for you. 

I have already been using the current example config with the referenced open command, but that solution only worked until https://github.com/gokcehan/lf/commit/4a443cae58ffe417c4aebedd88aeae6380bf190c

> If not then you can just submit the above patch as a separate pull request (I think this should be treated separately to the loading message).
The solution is yours and I would rather prefer not to take credit for it. I don't mind helping out with more testing though.

> As for the directories issue, after some debugging I found that specifically for the code that handles directories, there was a race condition caused by the fact that the `previewLoading` flag was being set in a different thread, and sometimes the UI would get drawn before that happens. I have pushed another commit to fix this, would you be able to try again?

This fixes the preview message for directories as well, thank you very much.

**Comment by joelim-work** [comment]
Very well, I have submitted #1164 to address the refreshing preview issue.

**Comment by bluesuncat** [comment]
> Very well, I have submitted #1164 to address the refreshing preview issue.

Thank you. With #1154 and #1164 there should be no more avoidable flickering and the issue can hopefully be closed soon

**Comment by joelim-work** [comment]
Hi @bluesuncat ,

Just an update, since you have proven to be very interested in the progress of these changes:

- #1164 is now merged
- For #1154, after some discussion with @gokcehan, I have decided to remove the `previewtimeout` option and just stick with a hard-coded timeout of 100 milliseconds. I hope that is okay with you
