### ISSUE TITLE
Ueberzug image previews overflow if drawbox option is set

### ISSUE THREAD

**Issue by noib3** [gokcehan/lf#602]
When using ueberzug image previews as described in the wiki, the `drawbox` option isn't taken into account and some previews overflow into the border. I would post a screenshot but for some reason `import` doesn't work when trying to capture lf, I just get a black blob.

**Comment by slavistan** [comment]
I've had that problem in the past but it seems to have been resolved at some point. I've compiled `lf` from source ca. a week ago and it has been working ever since.

![image](https://user-images.githubusercontent.com/35600954/115956977-1ffa1c00-a500-11eb-9384-c7b7c9ac0d93.png)

What doesn't work is that when toggling borders the preview is not generated anew, causing `ueberzug`
 previews to be off.

![demo](https://user-images.githubusercontent.com/35600954/115957308-c4c92900-a501-11eb-9cfb-12f7007159fc.gif)

**Comment by gokcehan** [comment]
@slavistan You seem right. I thought we explicitly need to handle this while exporting coordinate variables but there is no need for that since window coordinates already take `drawbox` option into account.

I have now pushed a fix to flush the cache and renew the preview with `drawbox` option changes. I don't think there is anything else left for this issue.

**Comment by rockyzhang24** [comment]
Hello @gokcehan , 

This issue persists when I preview images using the icat of kitty terminal.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/11582667/156672570-0520d5eb-2154-46bb-8817-32129f040589.png">

Thank you.

**Comment by ItsRogueRen** [comment]
I'm having this issue as well, most noticeably on Konsole and Tilix (tilix has images outside the terminal entirely). However for me, at least in Konsole, it happens regardless of drawboxes being present or not. I am using ueberzug previews.

![image](https://user-images.githubusercontent.com/75085610/162637043-dc7efe3b-a03b-4f72-b2aa-2842ac5b3c74.png)


![image](https://user-images.githubusercontent.com/75085610/162637081-d0f36a91-428c-482e-981b-b667663d1027.png)
