### ISSUE TITLE
unknown option: colors

### ISSUE THREAD

**Issue by Durev** [gokcehan/lf#879]
## Expected Behavior
Same behavior as the `icons` option.

## Current Behavior
An `unknown option: colors` error message is displayed when running lf.
The `colors` file is loaded as expected though, whether the option is present or not.

## Steps to Reproduce
1. Install [version 27](https://github.com/gokcehan/lf/releases/tag/r27)
2. Use a minimal lfrc file with
```
set colors
```

## Detailed Description
As per the [wiki instructions](https://github.com/gokcehan/lf/wiki/Tutorial#colors-and-icons), I originally set both of these options in my lfrc file:
```
set icons
set colors
```

The `icons` option seems to be working as expected, allowing to enable/disable the icons display.

The `colors` option is not recognized.
After checking the [eval.go](https://github.com/gokcehan/lf/blob/master/eval.go) file, I noticed that `colors` does not seem to be in the list of supported options.

Not sure if this is an error in the wiki, an implementation bug, or if I missed something? 😅

**Comment by YuCao16** [comment]
Same Issue here, but the colors actually works.

However, I found the default color scheme quite dim, I am currently using the [vivid](https://github.com/sharkdp/vivid) theme and the result is as follows.
<img width="1920" alt="colorscheme" src="https://user-images.githubusercontent.com/62466929/181753279-5c8f14d9-3b40-4921-a2f4-cdb73371ddf8.png">
You can just comment out `set colors` in your `lfrc` and add `export LS_COLORS="$(vivid generate molokai)"` in your `.zshrc`, and run `source ~/.zshrc` to make it works.

**I don't mean to offend by saying that the default colour scheme is a bit dim, in fact I enjoy `lf` so much, it's an amazing project.**

**Comment by tejaswivg** [comment]
I have the same issue with powershell on windows.

**Comment by aatmasaat** [comment]
having same issue, hope it is fixed soon

**Comment by thisismygitrepo** [comment]
same

**Comment by ryouiki-tenkai** [comment]
I'm using version 29 and the `set colors` option still throws error `unkown option: colors`, I have colors file in my `~/.config/lf` directory along with icons file and icons work. Any idea how to fix colors?

**Comment by ilyagr** [comment]
According to the docs, the file should be named `~/.config/lf/colors` exactly (and either `C:\Users\<user>\AppData\Local\lf\colors` or `C:\ProgramData\lf\colors` on Windows). There is no `colors` option

**Comment by ryouiki-tenkai** [comment]
```bash
~/.config/lf ❯ ls
colors  icons  lfrc
~/.config/lf ❯
```

i have the necessary files, and I thought `set colors` is option to enable colors just like `set icons`

**Comment by ilyagr** [comment]
No, there is no such option. Colors are always on.

Perhaps it would help if you shared the `colors` file. Also, what exactly is wrong with the colors you are seeing?

**Comment by ryouiki-tenkai** [comment]
nothing wrong, I thought I had to explicitly enable colors to see them but as colors are always on there is no further issue. The `colors` and `icons` files are taken from the repository. Have used below commands from [colors and icons](https://github.com/gokcehan/lf/wiki/Colors-and-Icons) section from wiki

```bash
mkdir -p ~/.config/lf
curl https://raw.githubusercontent.com/gokcehan/lf/master/etc/colors.example -o ~/.config/lf/colors
curl https://raw.githubusercontent.com/gokcehan/lf/master/etc/icons.example -o ~/.config/lf/icons
```

**Comment by gokcehan** [comment]
This was probably an error in the wiki. I don't think we ever had an option named `colors` as there is no need for such an option. Option `icons` is required since it changes the layout of panes. Colors are automatically enabled instead.

At some point we had an option `colors256` to switch between 16 and 256 colors but we removed it a long time ago after we switched from termbox to tcell since there was no need for such an option anymore.

Let me know if there is mention of an option named `colors` somewhere in the wiki pages. Closing this issue for now.
